### ISSUE TITLE
How to change domain in github pages for this repository?

### ISSUE THREAD

**Issue by freedoomacademy** [freedoomacademy/testReact#5]

**Comment by joanromerodev** [comment]
Under your repository name, click Settings. If you cannot see the "Settings" tab, select the dropdown menu, then click Settings. In the "Code and automation" section of the sidebar, click Pages. Under "Custom domain", type your custom domain, then click Save.

**Comment by freedoomacademy** [comment]
> Under your repository name, click Settings. If you cannot see the "Settings" tab, select the dropdown menu, then click Settings. In the "Code and automation" section of the sidebar, click Pages. Under "Custom domain", type your custom domain, then click Save.

Thank you!
